### ISSUE TITLE
Forked project to my account

### ISSUE THREAD

**Issue by Dr-Drive** [mradway/hycohanz#117]
Hey mradway, I forked your project to my account. 
I have added several changes. Feel free to pull my commits to your library after proper polishing, I tend to be sloppy some times when I get excited about something. All changes are operational as of now.
Check out the forked project at 
https://github.com/Dr-Drive/hycohanz

**Comment by mradway** [comment]
These look great.  Just keep pushing your changes, and I'll merge them in
as time permits.

**Comment by mradway** [comment]
I just merged all of your commits up to this point in a series of commits from 96f7c74 to 717f1c8.  Definitely some good stuff in there. I just made some minor edits to formatting, docstrings, and import conventions.
